spring:
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: false
    hibernate:
      use-new-id-generator-mappings: true
      
    
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    jmx-enabled: true
    url: "jdbc:mysql://online.hot365.xyz:33306/user?useSSL=false&characterEncoding=UTF-8&useUnicode=true"
    username: root                     # 数据库登陆名
    password: 619137943@qq.com                 # 数据库登陆密码
    hikari: 
      auto-commit: true

  jmx:
    enabled: false
  profiles:
    active:
      - dubbo
  dubbo:
    application:
      name: jpa-provider 
    provider:                  # 公用的生产者配置
      retries: -1              # 可选 性能调优 远程服务调用重试次数，不包括第一次调用，不需要重试请设为0 2.0.5以上版本
      accesslog: false         # 可选 服务治理 设为true，将向logger中输出访问日志，也可填写访问日志文件路径，直接把访问日志输出到指定文件 2.0.5以上版本
      token: true              # 可选 服务治理 令牌验证，为空表示不开启，如果为true，表示随机生成动态令牌 2.0.5以上版本
#      filter: providerFilter   # 可选 性能调优 服务提供方远程调用过程拦截器名称，多个名称用逗号分隔 2.0.5以上版本
      registry: test              # 可选 配置关联 向指定注册中心注册，在多个注册中心时使用，值为spring.dubbo.registry.的id属性，多个注册中心ID用逗号分隔，如果不想将该服务注册到任何registry，可将值设为N/A 2.0.5以上版本
#      protocol: dubbo-jvm         # 可选 性能调优 协议名称 1.0.16以上版本